trigger:
- master

pool:
  name: 'Default'
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'Install dependencies'

- script: |
    npm run lint
  displayName: 'Run linter'

- script: |
    npm run test
  displayName: 'Run tests'

- script: |
    npm ci # Clean install to ensure dependencies are up-to-date
    npm run build
  displayName: 'Build project'

- task: CopyFiles@2
  inputs:
    contents: '_buildOutput/**'
    targetFolder: $(Build.ArtifactStagingDirectory)
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: $(Build.ArtifactStagingDirectory)
    artifactName: MyBuildOutputs
